---
title: "Biostat Lab"
description: |
  The homepage for DGHI Biostat & Epi lab assignments, help pages, and whirly gigs
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


## Welcome!

This is the DGHI Biostatistics lab assignment homepage. Save this site's link to your bookmark browser and return here to access lab materials. Navigate to the various labs and help documents using the bar at the top of the page.

## A quick note on R and RStudio:

For this lab, you are going to need to download [R and RStudio](https://www.rstudio.com/products/rstudio/download/#download), a pair of free open-source softwares used for everything from data analysis to web design. 

## A reminder on broken code

Don't hesitate to ask for help if you are having problems with software, code, etc. But be warned, your question should be specific and detailed, not just "Why won't this line of code run?"

In my experience, unsent emails are sometimes better than (and faster) than a TA. What looks like a hairy knot in your code is often quick to untangle when you start putting things in writing. This is why we ask that any email you send be both detailed and  specific. 

Here are some other things that seem to help get your code to work:
* Go for a walk (seriously, maybe you've been sitting for too long)
* Google your error message -- there's almost always someone else who has encountered a similar problem
* Don't delete and make changes to the same line of code. Copy/paste into a new chunk. Formulate a hypothesis. Make changes. Take notes on what changed. Revise your hypothesis. Repeat.
* Learn the R Debugger

You might also flip through [this article on commmon problems in R Markdown](https://rmd4sci.njtierney.com/common-problems-with-rmarkdown-and-some-solutions.html), which might provide some answers. 


